import { createHash } from "node:crypto";
import { PDFDocument, StandardFonts, rgb } from "pdf-lib";
import type { AgreementTerms, FeeAllocation, PartyRole } from "@/lib/agreements/agreementService";
import type { PaymentFrequency, ScheduleItem } from "@/lib/agreements/schedule";

/**
 * Decision 9 (PDF/print fix — confirmed defect closure): deliberately carries NO profile/user id at
 * all — the prior shape (`ProfileRef & {displayName}`) is exactly what let a raw internal profile
 * UUID get printed into the legal document. `firstName`/`lastName`/`preferredEmail`/`city`/`state`/
 * `postalCode`/`country` come from the immutable agreement-party snapshot (Decision 7) once one
 * exists; `displayName` alone is the fallback for a business party or a legacy pre-snapshot
 * agreement (Decision 11) — never phone, never a street address, never any internal identifier.
 */
export interface AgreementPdfParty {
  displayName: string;
  firstName: string | null;
  lastName: string | null;
  preferredEmail: string | null;
  city: string | null;
  state: string | null;
  postalCode: string | null;
  country: string | null;
}

/** Decision 8/9: "First Name Last Name / preferred email / City, State ZIP" when a full snapshot is available; falls back to just the display name otherwise — never a raw id either way. */
function formatPartyLine(party: AgreementPdfParty): string {
  const nameLine = party.firstName && party.lastName ? `${party.firstName} ${party.lastName}` : party.displayName;
  const parts = [nameLine];
  if (party.preferredEmail) parts.push(party.preferredEmail);
  const cityState = [party.city, party.state].filter(Boolean).join(", ");
  const location = [cityState, party.postalCode].filter(Boolean).join(" ").trim();
  if (location) parts.push(party.country && party.country !== "US" ? `${location}, ${party.country}` : location);
  return parts.join(" — ");
}

export interface AgreementPdfSignature {
  role: PartyRole;
  signerDisplayName: string;
  signedAt: Date;
  authMethod: string;
}

/**
 * Sprint 6 (docs/sprints/SPRINT_06_ElectronicSignatures_PDFRecords.md) required PDF content:
 * agreement number, parties, debt purpose, financial terms, payment schedule, fees, no-interest
 * terms, amendment terms, payment authorization placeholder, signatures, witness attestations
 * where applicable, agreement version, hash/reference.
 */
export interface AgreementPdfInput {
  agreementId: string;
  versionNumber: number;
  relationshipShape: "P2P" | "B2C" | "C2B" | "B2B";
  currency: string;
  creditor: AgreementPdfParty;
  debtor: AgreementPdfParty;
  terms: AgreementTerms;
  frequency: PaymentFrequency;
  feeAllocation: FeeAllocation;
  schedule: ScheduleItem[];
  signatures: AgreementPdfSignature[];
  documentHash: string;
  // PRSprint 12 (docs/prsprints/PRSPRINT_12_ELECTRONIC_SIGNATURES_PDFS_IMMUTABLE_RECORDS.md):
  // execution/document identifier, printed in the document itself so a saved/printed copy can be
  // cross-referenced against its own agreement_pdf.id — generated by the caller *before* rendering
  // (see SignatureService.generatePdf) so it can be included here rather than learned only after the
  // row exists.
  executionId: string;
  // Trusted server time this document was generated — never a browser-supplied value.
  generatedAt: Date;
  // Null for an original (non-amended) version; set when this version was produced by an amendment,
  // so the static "no amendment has been made" claim isn't printed on a version that resulted from
  // one (PRSprint 11 integration — see this file's own "Amendment terms" section below).
  amendmentReference: { versionNumber: number; parentVersionNumber: number } | null;
  /**
   * Agreement Lifecycle V2 (Part 6 — Print/PDF): true only once both parties have signed this exact
   * version — "a negotiation version must never be misrepresented as an executed agreement." When
   * false, a prominent DRAFT banner is drawn and the document is generated fresh on every request
   * (never stored) rather than the one-time, immutable executed PDF SignatureService.generatePdf
   * produces — "never generate the executed PDF from newer mutable agreement data."
   */
  isFullyExecuted: boolean;
}

function formatDollars(minorUnits: number, currency: string): string {
  return `${(minorUnits / 100).toFixed(2)} ${currency}`;
}

const PAGE_SIZE: [number, number] = [612, 792]; // US Letter, points
const MARGIN = 54;
const LINE_HEIGHT = 16;

/**
 * Renders the immutable agreement PDF. This sprint's "hash stability" requirement is satisfied by
 * generating exactly once per version — never regenerating (agreement_pdf's unique index on
 * agreement_version_id enforces this at the DB level, and SignatureService checks for an existing
 * row before calling this) — and by hashing the resulting bytes immediately and storing that hash
 * alongside them, so the recorded hash and the stored file can always be re-verified against each
 * other later. This function is not guaranteed to produce byte-identical output across independent
 * calls with the same input (pdf-lib does not promise that), so hash stability is a property of
 * "generate once, hash what you generated, never regenerate" — not of the renderer being a pure
 * function.
 */
export async function generateAgreementPdf(input: AgreementPdfInput): Promise<Uint8Array> {
  const doc = await PDFDocument.create();
  const font = await doc.embedFont(StandardFonts.Helvetica);
  const boldFont = await doc.embedFont(StandardFonts.HelveticaBold);

  let page = doc.addPage(PAGE_SIZE);
  let y = PAGE_SIZE[1] - MARGIN;

  function newPageIfNeeded(linesNeeded = 1): void {
    if (y - linesNeeded * LINE_HEIGHT < MARGIN) {
      page = doc.addPage(PAGE_SIZE);
      y = PAGE_SIZE[1] - MARGIN;
    }
  }

  function heading(text: string): void {
    newPageIfNeeded(2);
    page.drawText(text, { x: MARGIN, y, size: 13, font: boldFont, color: rgb(0, 0, 0) });
    y -= LINE_HEIGHT * 1.5;
  }

  function line(text: string): void {
    newPageIfNeeded();
    page.drawText(text, { x: MARGIN, y, size: 10, font, color: rgb(0.1, 0.1, 0.1) });
    y -= LINE_HEIGHT;
  }

  heading("PAY2PAY Repayment Agreement");
  if (!input.isFullyExecuted) {
    page.drawText("DRAFT — NOT YET FULLY EXECUTED", { x: MARGIN, y, size: 12, font: boldFont, color: rgb(0.7, 0.1, 0.1) });
    y -= LINE_HEIGHT;
    line("This version has not been signed by both parties and is not yet a binding agreement.");
    y -= LINE_HEIGHT / 2;
  }
  line(`Agreement number: ${input.agreementId}`);
  line(`Agreement version: ${input.versionNumber}`);
  line(`Document/execution ID: ${input.executionId}`);
  line(`Generated: ${input.generatedAt.toISOString()}`);
  line(`Relationship type: ${input.relationshipShape}`);
  line(`Currency: ${input.currency}`);
  y -= LINE_HEIGHT / 2;

  heading("Electronic record disclosure");
  line("The parties have consented to conduct this transaction by electronic means. This document");
  line("is an electronic record of a repayment agreement executed via electronic signature on the");
  line("PAY2PAY platform. It is intended to be a legally binding record of the parties' agreement,");
  line("to the same extent as a signed paper original, consistent with applicable electronic");
  line("signature and records law (e.g. the U.S. ESIGN Act and UETA).");
  y -= LINE_HEIGHT / 2;

  heading("Parties");
  line(`Creditor: ${formatPartyLine(input.creditor)}`);
  line(`Debtor: ${formatPartyLine(input.debtor)}`);
  y -= LINE_HEIGHT / 2;

  heading("Debt purpose and financial terms");
  line(`Category: ${input.terms.category}`);
  line(`Description: ${input.terms.description}`);
  line(`Original amount: ${formatDollars(input.terms.originalAmountMinorUnits, input.currency)}`);
  line(`Previous payments: ${formatDollars(input.terms.previousPaymentsMinorUnits, input.currency)}`);
  line(`Current principal: ${formatDollars(input.terms.currentPrincipalMinorUnits, input.currency)}`);
  line(`Recurring installment: ${formatDollars(input.terms.installmentAmountMinorUnits, input.currency)} (${input.frequency})`);
  line(`Final payment: ${formatDollars(input.terms.finalPaymentMinorUnits, input.currency)}`);
  line(`Fee allocation: ${input.feeAllocation.replaceAll("_", " ")}`);
  y -= LINE_HEIGHT / 2;

  heading("No-interest terms");
  line("This agreement carries no interest, no compounding, and no percentage-based or");
  line("time-based late fees. Any disclosed fee is fixed and non-time-based.");
  y -= LINE_HEIGHT / 2;

  heading("Payment schedule");
  for (const item of input.schedule) {
    line(
      `${item.sequenceNumber === 0 ? "First payment" : `Installment ${item.sequenceNumber}`}: ` +
        `${formatDollars(item.amountMinorUnits, input.currency)} due ${item.dueDate}`,
    );
  }
  y -= LINE_HEIGHT / 2;

  heading("Early payoff, hardship, partial payment, and settlement terms");
  line(`Early payoff: ${input.terms.earlyPayoffTerms}`);
  line(`Hardship: ${input.terms.hardshipRules}`);
  line(`Partial payment: ${input.terms.partialPaymentRules}`);
  line(`Settlement: ${input.terms.settlementRules}`);
  y -= LINE_HEIGHT / 2;

  heading("Dispute procedure");
  line(input.terms.disputeProcedure);
  y -= LINE_HEIGHT / 2;

  heading("Amendment terms");
  line("This agreement may only be changed by mutual signature on a new agreement version.");
  if (input.amendmentReference) {
    line(
      `This is version ${input.amendmentReference.versionNumber}, resulting from an amendment to ` +
        `version ${input.amendmentReference.parentVersionNumber}. The prior version remains preserved,`,
    );
    line("unchanged, and separately retrievable in the agreement's version history.");
  } else {
    line("No amendment has been made to this agreement as of this document's generation.");
  }
  y -= LINE_HEIGHT / 2;

  heading("Payment authorization");
  line("Reserved for a later phase — no payment method has been authorized as part of");
  line("signing this agreement. Live payment processing is not implemented yet.");
  y -= LINE_HEIGHT / 2;

  heading("Signatures");
  if (input.signatures.length === 0) {
    line("Not yet signed by either party.");
  } else {
    for (const signature of input.signatures) {
      line(
        `${signature.role}: ${signature.signerDisplayName} — signed ${signature.signedAt.toISOString()} ` +
          `(${signature.authMethod})`,
      );
    }
    if (!input.isFullyExecuted) {
      line("Awaiting the remaining party's signature.");
    }
  }
  y -= LINE_HEIGHT / 2;

  heading("Witness attestations");
  line("None recorded. Witness attestations are a later-phase feature.");
  y -= LINE_HEIGHT / 2;

  heading("Document reference");
  line(`Terms hash: ${input.documentHash}`);

  return doc.save();
}

/** Tamper-evident hash of the final rendered PDF bytes, stored on agreement_pdf.document_hash. */
export function hashPdfContent(bytes: Uint8Array): string {
  return createHash("sha256").update(bytes).digest("hex");
}
