"use client";
import Link from "next/link";
import { usePathname, useRouter } from "next/navigation";
import { useEffect, useState } from "react";

interface ActiveProfileSummary{kind:"personal"|"business";displayName:string}
interface WorkspaceListItem{organizationId:string;displayName:string}
const PERSONAL_LINKS=[{href:"/dashboard",label:"Dashboard"},{href:"/agreements",label:"Agreements"},{href:"/payments",label:"Payments"},{href:"/connections",label:"Connections"}];
const ACCOUNT_LINKS=[{href:"/account",label:"Profile & Settings"},{href:"/account/security",label:"Security"},{href:"/account/verification",label:"Verification"},{href:"/support",label:"Support"}];
export const BUSINESS_NAV_ITEMS=[{path:"",label:"Dashboard",group:null},{path:"/balances",label:"Outstanding Balances",group:"MONEY & CUSTOMERS"},{path:"/customers",label:"Customers",group:"MONEY & CUSTOMERS"},{path:"/agreements",label:"Agreements",group:"MONEY & CUSTOMERS"},{path:"/employees",label:"Employees",group:"TEAM"},{path:"/settings",label:"Organization Settings",group:"ADMINISTRATION"},{path:"/settings/billing",label:"Billing & Subscription",group:"ADMINISTRATION"}] as const;

function Gateway({kind,active,signInHref,createHref}:{kind:"business"|"personal";active:boolean;signInHref:string;createHref:string}){const business=kind==="business";return <div className={`app-nav__gateway${active?" app-nav__gateway--active":""}`}><span className={`app-nav__gateway-badge app-nav__gateway-badge--${kind}`} aria-hidden="true">{business?"B":"P"}</span><div className="app-nav__gateway-copy"><strong>{business?"Paid2You":"My Paid2You"}</strong><span>{business?"Business":"Personal"}</span></div><div className="app-nav__gateway-actions">{active?<span className="app-nav__gateway-current">Current</span>:<><Link href={signInHref}>Sign in</Link><Link href={createHref}>Create</Link></>}</div></div>}
function BusinessNav({organizationId,pathname}:{organizationId:string;pathname:string}){const groups=[null,"MONEY & CUSTOMERS","TEAM","ADMINISTRATION"] as const;return <>{groups.map(group=><div className="app-nav__section" key={group??"dashboard"}>{group?<span className="app-nav__section-label">{group}</span>:null}{BUSINESS_NAV_ITEMS.filter(i=>i.group===group).map(i=>{const href=`/organizations/${organizationId}${i.path}`;const active=pathname===href;return <Link key={href} href={href} className={`app-nav__link${active?" app-nav__link--active":""}`} aria-current={active?"page":undefined}>{i.label}</Link>})}</div>)}</>}
function PendingBusinessNav(){return <><div className="app-nav__section"><div className="app-nav__link app-nav__link--active">Create Business Account</div></div><div className="app-nav__section"><span className="app-nav__section-label">MONEY & CUSTOMERS</span>{["Outstanding Balances","Customers","Agreements"].map(x=><div key={x} className="app-nav__link app-nav__link--disabled" aria-disabled="true">{x}</div>)}</div><div className="app-nav__section"><span className="app-nav__section-label">TEAM</span><div className="app-nav__link app-nav__link--disabled" aria-disabled="true">Employees</div></div><div className="app-nav__section"><span className="app-nav__section-label">ADMINISTRATION</span>{["Organization Settings","Billing & Subscription"].map(x=><div key={x} className="app-nav__link app-nav__link--disabled" aria-disabled="true">{x}</div>)}</div></>}

export function AppNav(){const pathname=usePathname();const router=useRouter();const[email,setEmail]=useState<string|null>(null);const[activeProfile,setActiveProfile]=useState<ActiveProfileSummary|null>(null);const[organizations,setOrganizations]=useState<WorkspaceListItem[]>([]);const[mobileNavOpen,setMobileNavOpen]=useState(false);const[lastPath,setLastPath]=useState(pathname);if(pathname!==lastPath){setLastPath(pathname);setMobileNavOpen(false)}
useEffect(()=>{let cancelled=false;fetch("/api/auth/me").then(async r=>{if(cancelled||!r.ok)return;const b=await r.json() as{email:string};if(!cancelled)setEmail(b.email)}).catch(()=>{});fetch("/api/profiles/active").then(async r=>{if(cancelled||!r.ok)return;const b=await r.json() as ActiveProfileSummary;if(!cancelled)setActiveProfile(b)}).catch(()=>{if(!cancelled)setActiveProfile(null)});fetch("/api/organizations").then(async r=>{if(cancelled||!r.ok)return;const b=await r.json() as{organizations:WorkspaceListItem[]};if(!cancelled)setOrganizations(b.organizations)}).catch(()=>{if(!cancelled)setOrganizations([])});return()=>{cancelled=true}},[pathname]);
const match=/^\/organizations\/([^/]+)/.exec(pathname);const rawOrg=match?.[1]??null;const activeOrg=rawOrg&&rawOrg!=="new"?rawOrg:null;const businessContext=pathname.startsWith("/organizations")||activeProfile?.kind==="business";const businessHome=activeOrg?`/organizations/${activeOrg}`:organizations[0]?`/organizations/${organizations[0].organizationId}`:"/organizations/new";
async function logout(){await fetch("/api/auth/logout",{method:"POST"});router.push("/login");router.refresh()}
const businessSignIn=`/login?accountType=business&next=${encodeURIComponent(businessHome)}`;const personalSignIn=`/login?accountType=personal&next=${encodeURIComponent("/dashboard")}`;
return <><div className="app-topbar"><Link className="app-topbar__brand paid2you-wordmark" href={businessContext?businessHome:"/dashboard"}><span>Paid2</span><strong>You</strong></Link><div className="app-topbar__actions"><button type="button" className="app-topbar__button" aria-expanded={mobileNavOpen} aria-controls="app-primary-nav" onClick={()=>setMobileNavOpen(o=>!o)}>{mobileNavOpen?"Close":"Menu"}</button><button type="button" className="app-topbar__button app-topbar__logout" onClick={()=>void logout()}>Log out</button></div></div><nav id="app-primary-nav" className={`app-nav${mobileNavOpen?" app-nav--mobile-open":""}`} aria-label="Primary"><div className="app-nav__header"><Link className="app-nav__brand paid2you-wordmark" href={businessContext?businessHome:"/dashboard"}><span>Paid2</span><strong>You</strong></Link><button type="button" className="app-nav__close" aria-label="Close menu" onClick={()=>setMobileNavOpen(false)}>Close</button></div><div className="app-nav__gateways"><Gateway kind="business" active={businessContext} signInHref={businessSignIn} createHref="/organizations/new"/><Gateway kind="personal" active={!businessContext} signInHref={personalSignIn} createHref="/signup?accountType=personal"/></div><div className="app-nav__divider"/>{businessContext?(activeOrg?<BusinessNav organizationId={activeOrg} pathname={pathname}/>:<PendingBusinessNav/>):<div className="app-nav__section">{PERSONAL_LINKS.map(i=><Link key={i.href} href={i.href} className={`app-nav__link${pathname===i.href?" app-nav__link--active":""}`} aria-current={pathname===i.href?"page":undefined}>{i.label}</Link>)}</div>}<div className="app-nav__divider"/><div className="app-nav__section"><span className="app-nav__section-label">ACCOUNT</span>{ACCOUNT_LINKS.map(i=><Link key={i.href} href={i.href} className={`app-nav__link${pathname===i.href?" app-nav__link--active":""}`}>{i.label}</Link>)}</div><div className="app-nav__footer">{email?<div className="app-nav__user"><strong>Signed in as</strong><span>{email}</span></div>:null}<button type="button" className="app-nav__logout" onClick={()=>void logout()}>Log out</button></div></nav></>}
